language: python
python:
  - 2.7


notifications:
  email: false
 
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install pyliblzma; fi
  - travis_retry pip install coveralls
  - travis_retry python setup.py install
 # add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# Run test
script:
  - nosetests --verbose --with-coverage --cover-branches --cover-package=abydos --logging-level=INFO --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_abydos_24d1dac3fc_4
  - python -m properform Push 47.88.50.110:15554 asdf_abydos_24d1dac3fc_4 ./profile_abydos_24d1dac3fc_4


 
# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
 #2017-08-12 20:37:32 modified at 0 #2017-08-12 20:37:38 modified at 1 #2017-08-12 20:37:44 modified at 2 #2017-08-12 20:37:49 modified at 3 #2017-08-12 20:37:55 modified at 4