language: python
python:
  - 2.7


notifications:
  email: false
 

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# Install packages
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install pyliblzma; fi
  - travis_retry pip install coveralls
  - travis_retry python setup.py install
 # add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# Run test
script:
  - nosetests --verbose --with-coverage --cover-branches --cover-package=abydos --logging-level=INFO --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_abydos_154127fd38_0
  - python -m properform Push 47.88.50.110:15554 asdf_abydos_154127fd38_0 ./profile_abydos_154127fd38_0


 
# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
 #2017-08-12 20:02:31 modified at 0