language: python
python:
  - 2.7
  #- pypy

notifications:
  email: false
 
before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# Install packages
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install pyliblzma; fi
  - travis_retry pip install coveralls
  - travis_retry python setup.py install
 # add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# Run test
script:
  - nosetests --verbose --with-coverage --cover-branches --cover-package=abydos --logging-level=INFO --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_abydos_f2f7cb434b_4
  - python -m properform Push 47.88.50.110:15554 asdf_abydos_f2f7cb434b_4 ./profile_abydos_f2f7cb434b_4
 
# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
 #2017-08-12 19:59:51 modified at 0 #2017-08-12 19:59:58 modified at 1 #2017-08-12 20:00:03 modified at 2 #2017-08-12 20:00:10 modified at 3 #2017-08-12 20:00:15 modified at 4